// =============================================================
// 블로그 메타데이터 인덱스 (본문 미포함 — 클라이언트 번들 최적화)
// =============================================================

export type {
  BlogPost,
  BlogPostMeta,
  BlogPostSection,
  BlogCategory,
  BlogCategoryValue,
} from "./types";
export { BLOG_CATEGORIES, BLOG_TAGS } from "./types";
export { categoryColors } from "./category-colors";

import type { BlogPostMeta } from "./types";

/** 목록용 메타데이터 배열 (본문 content 미포함) */
export const BLOG_POSTS_META: BlogPostMeta[] = [
  {
    id: 1,
    slug: "correct-brushing-method",
    category: "예방·구강관리",
    tags: [],
    title: "매일 닦는데 왜 충치가 생길까요?",
    subtitle: "올바른 양치질 방법과 치과 전문의의 핵심 팁",
    excerpt:
      "매일 하는 양치질이지만 올바른 방법을 모르는 경우가 많습니다. 칫솔 각도 45도, 잇몸에서 치아 방향으로 쓸어내기 등 치과 전문의가 알려주는 올바른 양치법을 확인해 보세요.",
    date: "2026-02-10",
    readTime: "3분",
  },
  {
    id: 2,
    slug: "implant-aftercare-tips",
    category: "임플란트",
    tags: ["치료후관리"],
    title: "임플란트, 심으면 끝일까요?",
    subtitle: "임플란트 수명을 결정하는 관리법 5가지",
    excerpt:
      "임플란트 시술 후 올바른 관리가 수명을 결정합니다. 정기 검진, 올바른 양치법, 워터픽 사용법 등 임플란트를 오래 사용하기 위한 핵심 관리 방법을 소개합니다.",
    date: "2026-02-08",
    readTime: "4분",
  },
  {
    id: 3,
    slug: "children-dental-care",
    category: "소아치료",
    tags: [],
    title: "첫 치과, 타이밍이 중요합니다",
    subtitle: "우리 아이 첫 치과 방문 시기와 준비 가이드",
    excerpt:
      "아이의 유치가 나기 시작하면 치과 검진을 시작하는 것이 좋습니다. 첫 치과 방문 시기, 소아 불소 도포의 효과, 아이가 치과를 무서워하지 않게 하는 방법까지 알아봅니다.",
    date: "2026-02-05",
    readTime: "5분",
  },
  {
    id: 4,
    slug: "gum-disease-prevention",
    category: "예방·구강관리",
    tags: ["증상가이드"],
    title: "양치할 때 피가 나요",
    subtitle: "잇몸 질환 초기 증상과 예방법",
    excerpt:
      "양치할 때 잇몸에서 피가 나거나 붓는 증상은 잇몸 질환의 초기 신호일 수 있습니다. 치은염과 치주염의 차이, 초기에 발견하고 관리하는 방법을 알아봅니다.",
    date: "2026-02-03",
    readTime: "4분",
  },
  {
    id: 5,
    slug: "food-for-dental-health",
    category: "예방·구강관리",
    tags: ["생활습관"],
    title: "먹는 것이 치아를 결정합니다",
    subtitle: "치아 건강에 좋은 음식 vs 나쁜 음식",
    excerpt:
      "우유, 치즈, 녹차 등 치아를 보호하는 음식과 탄산음료, 끈적한 캔디 등 치아에 해로운 음식을 비교해 봅니다. 식습관만 바꿔도 충치 예방에 큰 도움이 됩니다.",
    date: "2026-01-29",
    readTime: "3분",
  },
  {
    id: 6,
    slug: "dental-floss-guide",
    category: "예방·구강관리",
    tags: [],
    title: "양치만으로는 40%가 부족합니다",
    subtitle: "치실의 필요성과 올바른 사용법 가이드",
    excerpt:
      "양치만으로는 치아 사이 음식물과 플라크를 완전히 제거할 수 없습니다. 치실과 치간칫솔의 올바른 사용법, 그리고 자신에게 맞는 제품을 고르는 방법을 안내합니다.",
    date: "2026-01-25",
    readTime: "3분",
  },
  {
    id: 7,
    slug: "teeth-sensitivity-causes",
    category: "구강건강상식",
    tags: ["증상가이드"],
    title: "찬물 마시면 이가 시려요",
    subtitle: "시린 치아의 원인과 대처법 총정리",
    excerpt:
      "시린 이의 원인은 잇몸 퇴축, 법랑질 손상, 충치 등 다양합니다. 시린 이 전용 치약의 효과, 병원에서 받을 수 있는 치료, 일상에서의 관리법을 함께 알아봅니다.",
    date: "2026-01-22",
    readTime: "4분",
  },
  {
    id: 8,
    slug: "scaling-myths-and-facts",
    category: "예방·구강관리",
    tags: ["팩트체크"],
    title: "스케일링하면 이가 깎인다?",
    subtitle: "스케일링에 대한 흔한 오해와 진실",
    excerpt:
      "스케일링 후 이가 시리거나 벌어진 느낌이 드는 이유, 1년에 한 번 건강보험 적용 스케일링의 중요성 등 스케일링에 대한 흔한 오해와 정확한 정보를 정리했습니다.",
    date: "2026-01-18",
    readTime: "3분",
  },
  {
    id: 9,
    slug: "orthodontics-for-adults",
    category: "치아교정",
    tags: ["팩트체크"],
    title: "교정은 어릴 때만? 아닙니다",
    subtitle: "성인 교정에 대한 궁금증 총정리",
    excerpt:
      "치아 교정은 성인이 되어도 가능합니다. 투명교정, 설측교정 등 다양한 옵션과 교정 기간, 비용, 일상생활에서의 주의사항을 정리했습니다.",
    date: "2026-01-14",
    readTime: "5분",
  },
  {
    id: 10,
    slug: "stress-and-teeth-grinding",
    category: "구강건강상식",
    tags: ["생활습관", "증상가이드"],
    title: "자고 나면 턱이 뻐근해요",
    subtitle: "이갈이의 원인과 방치하면 안 되는 이유",
    excerpt:
      "스트레스, 수면 자세, 교합 문제 등으로 발생하는 이갈이는 치아 마모, 턱관절 장애로 이어질 수 있습니다. 자가 진단법과 치과에서의 치료법을 소개합니다.",
    date: "2026-01-10",
    readTime: "4분",
  },
  {
    id: 11,
    slug: "bad-breath-causes-and-solutions",
    category: "구강건강상식",
    tags: ["증상가이드"],
    title: "입 냄새가 나는 것 같아요",
    subtitle: "구취의 원인부터 해결법까지",
    excerpt:
      "구취의 약 90%는 구강 내 원인에서 발생합니다. 혀 세균, 잇몸 질환, 구강 건조증 등 입 냄새의 주요 원인과 근본적인 해결 방법을 치과 전문의가 알려드립니다.",
    date: "2026-01-07",
    readTime: "4분",
  },
  {
    id: 12,
    slug: "cavity-stages-and-treatment",
    category: "보존치료",
    tags: [],
    title: "충치도 단계가 있습니다",
    subtitle: "단계별로 달라지는 충치 치료법 총정리",
    excerpt:
      "초기 충치는 불소 치료만으로 회복될 수 있지만, 진행되면 신경치료나 발치가 필요합니다. 충치의 진행 단계별 증상과 치료 방법을 알기 쉽게 정리했습니다.",
    date: "2026-01-04",
    readTime: "4분",
  },
  {
    id: 13,
    slug: "teeth-whitening-safety",
    category: "구강건강상식",
    tags: ["팩트체크"],
    title: "하얀 치아, 안전하게 가능할까?",
    subtitle: "치아 미백의 종류와 주의사항",
    excerpt:
      "누런 치아가 고민이라면 치아 미백을 고려해 보세요. 전문 미백과 자가 미백의 차이, 효과, 부작용, 그리고 미백 후 관리법까지 꼼꼼하게 알려드립니다.",
    date: "2025-12-30",
    readTime: "4분",
  },
  {
    id: 14,
    slug: "pregnancy-dental-care",
    category: "예방·구강관리",
    tags: ["임산부", "증상가이드"],
    title: "임신했는데 잇몸이 아파요",
    subtitle: "임산부가 꼭 알아야 할 구강 관리법",
    excerpt:
      "임신 중 호르몬 변화로 잇몸 출혈과 부종이 흔하게 나타납니다. 임산부가 알아야 할 구강 관리법, 치과 치료 시기, 입덧 시 양치 요령을 안내합니다.",
    date: "2025-12-26",
    readTime: "5분",
  },
  {
    id: 15,
    slug: "wisdom-teeth-extraction",
    category: "구강건강상식",
    tags: [],
    title: "사랑니, 남길까 뺄까?",
    subtitle: "발치가 필요한 기준과 수술 후 관리법",
    excerpt:
      "사랑니가 아프거나 잇몸이 붓는다면 발치를 고려해야 합니다. 사랑니를 빼야 하는 경우와 안 빼도 되는 경우, 발치 후 관리법을 정리했습니다.",
    date: "2025-12-22",
    readTime: "4분",
  },
  {
    id: 16,
    slug: "denture-vs-implant",
    category: "보철치료",
    tags: ["시니어", "비교가이드"],
    title: "틀니와 임플란트, 뭐가 나을까?",
    subtitle: "나에게 맞는 치아 보철 선택 가이드",
    excerpt:
      "치아를 상실했을 때 틀니와 임플란트 중 어떤 것이 좋을까요? 두 방법의 장단점, 적합한 대상, 비용 차이를 비교하여 올바른 선택을 도와드립니다.",
    date: "2025-12-18",
    readTime: "5분",
  },
  {
    id: 17,
    slug: "dry-mouth-syndrome",
    category: "구강건강상식",
    tags: ["생활습관", "증상가이드"],
    title: "입이 자꾸 말라요",
    subtitle: "구강 건조증의 원인과 관리법",
    excerpt:
      "입이 마르고 침이 부족하면 충치, 잇몸 질환, 구취의 위험이 높아집니다. 구강 건조증의 원인, 자가 관리법, 치과에서의 치료를 알아봅니다.",
    date: "2025-12-14",
    readTime: "4분",
  },
  {
    id: 18,
    slug: "toothbrush-hygiene-tips",
    category: "예방·구강관리",
    tags: [],
    title: "그 칫솔, 정말 깨끗한가요?",
    subtitle: "의외로 모르는 칫솔 세균 관리법",
    excerpt:
      "칫솔에는 양치 후 수백만 개의 세균이 남아 있을 수 있습니다. 올바른 칫솔 보관법, 교체 시기, 전동 칫솔 관리법까지 알아봅니다.",
    date: "2025-12-10",
    readTime: "3분",
  },
  {
    id: 19,
    slug: "diabetes-and-dental-health",
    category: "구강건강상식",
    tags: ["생활습관"],
    title: "당뇨가 치아를 망칠 수 있다?",
    subtitle: "당뇨와 치아 건강의 상호 관계",
    excerpt:
      "당뇨병 환자는 잇몸 질환 위험이 2~3배 높고, 반대로 잇몸 질환은 혈당 조절을 어렵게 합니다. 당뇨와 구강 건강의 관계를 알아봅니다.",
    date: "2025-12-06",
    readTime: "4분",
  },
  {
    id: 20,
    slug: "root-canal-and-crown",
    category: "보존치료",
    tags: ["비교가이드"],
    title: "신경치료 후에는 꼭 크라운을 씌워야 하나요?",
    subtitle: "신경치료 후 크라운이 반드시 필요한 이유",
    excerpt:
      "신경치료를 받은 치아는 내부가 비어 약해지기 때문에 크라운으로 보호해야 합니다. 신경치료의 과정, 크라운의 필요성, 종류별 특징을 알아봅니다.",
    date: "2025-12-02",
    readTime: "4분",
  },
  {
    id: 21,
    slug: "after-tooth-extraction-care",
    category: "보존치료",
    tags: ["치료후관리"],
    title: "발치 후 이것만은 피하세요",
    subtitle: "빠른 회복을 위한 발치 후 핵심 주의사항",
    excerpt:
      "발치 후 출혈, 통증, 붓기는 자연스러운 과정이지만, 관리를 잘못하면 합병증이 생길 수 있습니다. 발치 당일부터 완전 회복까지 단계별 주의사항을 안내합니다.",
    date: "2025-11-28",
    readTime: "4분",
  },
  {
    id: 22,
    slug: "after-implant-surgery-care",
    category: "임플란트",
    tags: ["치료후관리"],
    title: "임플란트 성공, 수술 후가 더 중요합니다",
    subtitle: "성공률을 높이는 임플란트 수술 후 관리법",
    excerpt:
      "임플란트 수술 후 초기 관리가 임플란트의 장기적 성공을 좌우합니다. 수술 직후부터 보철물 장착까지 단계별 주의사항을 자세히 안내합니다.",
    date: "2025-11-24",
    readTime: "5분",
  },
  {
    id: 23,
    slug: "after-root-canal-care",
    category: "보존치료",
    tags: ["치료후관리"],
    title: "신경치료 받은 치아, 오래 쓰려면",
    subtitle: "치아를 오래 보존하는 신경치료 후 주의사항",
    excerpt:
      "신경치료 중이거나 치료를 마친 후 통증과 관리가 걱정되시나요? 치료 중 주의할 점, 치료 후 통증 관리, 크라운까지의 과정을 안내합니다.",
    date: "2025-11-20",
    readTime: "4분",
  },
  {
    id: 24,
    slug: "after-scaling-care",
    category: "예방·구강관리",
    tags: ["치료후관리"],
    title: "스케일링 후 시리다고요? 정상입니다",
    subtitle: "스케일링 후 관리법과 주의사항",
    excerpt:
      "스케일링 후 이가 시리고 잇몸에서 피가 나나요? 대부분 자연스러운 반응입니다. 스케일링 후 나타나는 증상과 올바른 관리법을 안내합니다.",
    date: "2025-11-16",
    readTime: "4분",
  },
  {
    id: 25,
    slug: "after-filling-care",
    category: "보존치료",
    tags: ["치료후관리"],
    title: "충치 치료 후 바로 밥 먹어도 될까?",
    subtitle: "레진·인레이 치료 후 주의사항 총정리",
    excerpt:
      "충치 부위를 레진이나 인레이로 떼운 후 식사는 언제부터 가능할까요? 재료별 특성과 치료 후 관리법, 주의해야 할 증상을 알려드립니다.",
    date: "2025-11-12",
    readTime: "4분",
  },
  {
    id: 26,
    slug: "after-whitening-care",
    category: "구강건강상식",
    tags: ["치료후관리"],
    title: "미백 효과, 카레 한 끼에 사라진다?",
    subtitle: "치아 미백 효과를 오래 유지하는 관리법",
    excerpt:
      "미백 시술 후 48시간이 결과를 좌우합니다. 미백 후 피해야 할 음식, 시린 증상 대처법, 효과를 오래 유지하는 관리법을 안내합니다.",
    date: "2025-11-08",
    readTime: "4분",
  },
  {
    id: 27,
    slug: "after-orthodontic-device-care",
    category: "치아교정",
    tags: ["치료후관리"],
    title: "교정 장치, 처음이 가장 힘듭니다",
    subtitle: "부착 후 적응 기간 관리법과 주의사항",
    excerpt:
      "교정 장치를 처음 붙이면 통증과 불편감이 생깁니다. 장치 적응법, 피해야 할 음식, 교정 중 양치법, 장치 파손 시 대처법을 안내합니다.",
    date: "2025-11-04",
    readTime: "4분",
  },
  {
    id: 28,
    slug: "after-gum-surgery-care",
    category: "예방·구강관리",
    tags: ["치료후관리"],
    title: "잇몸 수술, 회복이 결과를 좌우합니다",
    subtitle: "잇몸 수술 후 회복을 돕는 핵심 관리법",
    excerpt:
      "잇몸 수술(치주 수술) 후 통증, 붓기, 출혈은 자연스러운 회복 과정입니다. 수술 후 식사, 양치, 약 복용 등 빠른 회복을 위한 관리법을 안내합니다.",
    date: "2025-10-30",
    readTime: "4분",
  },
  {
    id: 29,
    slug: "after-crown-prosthetic-care",
    category: "보철치료",
    tags: ["치료후관리", "증상가이드"],
    title: "크라운 씌웠는데 불편해요",
    subtitle: "크라운·브릿지 장착 후 주의사항 가이드",
    excerpt:
      "크라운이나 브릿지를 새로 씌운 후 적응 기간과 관리법이 궁금하신가요? 교합 적응, 식사 주의점, 장기 관리법을 알려드립니다.",
    date: "2025-10-26",
    readTime: "4분",
  },
  {
    id: 30,
    slug: "after-child-dental-treatment-care",
    category: "소아치료",
    tags: ["치료후관리"],
    title: "아이가 치과 치료 받고 왔다면",
    subtitle: "보호자가 꼭 알아야 할 치료 후 주의사항",
    excerpt:
      "아이가 치과 치료를 받은 후 보호자가 알아야 할 핵심 주의사항을 정리했습니다. 마취 후 관리, 식사 요령, 아이를 안심시키는 방법까지 안내합니다.",
    date: "2025-10-22",
    readTime: "4분",
  },
  {
    id: 31,
    slug: "dental-xray-radiation-safety",
    category: "구강건강상식",
    tags: ["팩트체크", "임산부"],
    title: "치과 엑스레이, 방사선이 걱정되시나요?",
    subtitle: "엑스레이 방사선 안전성의 모든 것",
    excerpt:
      "치과 진료 때마다 촬영하는 엑스레이, 방사선이 걱정되시나요? 파노라마·CT·치근단 촬영별 방사선량을 일상 피폭량과 비교하고, 안전하게 촬영받는 방법을 안내합니다.",
    date: "2026-02-13",
    readTime: "4분",
  },
  {
    id: 32,
    slug: "cracked-tooth-syndrome",
    category: "보존치료",
    tags: ["증상가이드"],
    title: "씹을 때 이가 시큰거려요",
    subtitle: "눈에 보이지 않는 치아 크랙의 원인과 치료",
    excerpt:
      "씹을 때 찌릿한 통증이 있지만 겉으로 이상이 없다면 치아 균열을 의심해 보세요. 치아 크랙의 원인, 단계별 증상, 진단 방법, 그리고 치료법까지 자세히 알려드립니다.",
    date: "2026-02-13",
    readTime: "5분",
  },
  {
    id: 33,
    slug: "denture-care-tips",
    category: "보철치료",
    tags: ["시니어", "치료후관리"],
    title: "틀니, 올바르게 관리하고 계신가요?",
    subtitle: "틀니 사용 시 꼭 알아야 할 관리법",
    excerpt:
      "틀니를 처음 사용하시거나 관리가 어려우신가요? 올바른 세척법, 착용 요령, 음식 주의사항, 정기 점검의 중요성까지 틀니 사용자라면 꼭 알아야 할 핵심 관리법을 안내합니다.",
    date: "2026-02-13",
    readTime: "5분",
  },
  {
    id: 34,
    slug: "clear-aligner-care-guide",
    category: "치아교정",
    tags: ["치료후관리"],
    title: "투명교정, 끼기만 하면 될까?",
    subtitle: "교정 효과를 높이는 투명교정 관리법",
    excerpt:
      "투명교정(클리어 얼라이너)을 시작하셨나요? 착용 시간, 식사 요령, 세척법, 통증 관리까지 교정 효과를 극대화하는 핵심 주의사항을 정리했습니다.",
    date: "2026-02-13",
    readTime: "5분",
  },
  {
    id: 35,
    slug: "implant-vs-bridge-comparison",
    category: "임플란트",
    tags: ["비교가이드"],
    title: "임플란트 vs 브릿지, 뭐가 나을까?",
    subtitle: "빈 치아 수복 방법 비교 가이드",
    excerpt:
      "치아를 상실했을 때 임플란트와 브릿지 중 어떤 치료가 나에게 맞을까요? 비용, 수명, 시술 기간, 인접 치아 영향까지 두 치료법의 장단점을 비교해 드립니다.",
    date: "2026-02-13",
    readTime: "5분",
  },
  {
    id: 36,
    slug: "implant-pain-myths",
    category: "임플란트",
    tags: ["팩트체크"],
    title: "\"임플란트 아프다\"는 말, 진짜일까?",
    subtitle: "임플란트 통증에 대한 오해와 진실",
    excerpt:
      "임플란트 시술을 망설이게 하는 가장 큰 이유, 통증. 실제로 얼마나 아픈지, 마취는 어떻게 하는지, 회복 기간의 불편감은 어떤지 솔직하게 알려드립니다.",
    date: "2026-02-13",
    readTime: "5분",
  },
  {
    id: 37,
    slug: "diabetes-and-implant",
    category: "임플란트",
    tags: ["생활습관", "시니어"],
    title: "당뇨가 있어도 임플란트 가능한가요?",
    subtitle: "전신 질환과 임플란트의 관계",
    excerpt:
      "당뇨병이 있으면 임플란트를 못 한다? 혈당 조절이 잘 되면 충분히 가능합니다. 당뇨 환자의 임플란트 시술 조건, 주의사항, 관리법을 정리했습니다.",
    date: "2026-02-13",
    readTime: "5분",
  },
  {
    id: 38,
    slug: "implant-lifespan-facts",
    category: "임플란트",
    tags: ["팩트체크"],
    title: "임플란트 수명, 10년? 30년?",
    subtitle: "오래 쓰는 사람들의 공통점 3가지",
    excerpt:
      "임플란트는 반영구적이라고 하는데, 실제 수명은 얼마나 될까요? 통계로 보는 임플란트 수명과, 오래 사용하는 사람들의 관리 비결을 알려드립니다.",
    date: "2026-02-13",
    readTime: "5분",
  },
  {
    id: 39,
    slug: "sealant-for-children",
    category: "소아치료",
    tags: [],
    title: "실란트, 꼭 해야 하나요?",
    subtitle: "우리 아이 충치 예방의 첫 번째 방패",
    excerpt:
      "어금니 홈을 메워 충치를 막는 실란트. 언제 하는 게 좋은지, 효과는 얼마나 되는지, 건강보험 적용은 되는지 소아치과 전문의 관점에서 정리했습니다.",
    date: "2026-02-14",
    readTime: "4분",
  },
  {
    id: 40,
    slug: "crown-material-comparison",
    category: "보철치료",
    tags: ["비교가이드"],
    title: "크라운, 어떤 재료가 오래 갈까?",
    subtitle: "지르코니아·골드·PFM 크라운 재료별 수명과 특징 비교",
    excerpt:
      "크라운 재료에 따라 수명, 심미성, 강도가 모두 다릅니다. 지르코니아, 골드, PFM 등 대표 크라운 재료의 장단점과 수명을 비교해 나에게 맞는 선택을 도와드립니다.",
    date: "2026-02-14",
    readTime: "5분",
  },
  {
    id: 41,
    slug: "airflow-scaling-benefits",
    category: "예방·구강관리",
    tags: ["비교가이드"],
    title: "에어플로우 스케일링, 뭐가 다른가요?",
    subtitle: "일반 초음파 스케일링과 에어플로우의 차이점 비교",
    excerpt:
      "스케일링이 아파서 미루고 계셨나요? 에어플로우 스케일링은 기존 초음파 방식보다 시린 증상과 불편감이 적습니다. 두 방식의 원리, 차이점, 장단점을 비교해 드립니다.",
    date: "2026-02-14",
    readTime: "4분",
  },
  {
    id: 42,
    slug: "implant-eligibility-checklist",
    category: "임플란트",
    tags: ["증상가이드"],
    title: "임플란트, 누구나 할 수 있을까?",
    subtitle: "시술 전 꼭 확인해야 할 건강 체크리스트",
    excerpt:
      "임플란트를 고려하고 있지만 나이, 만성질환, 뼈 상태가 걱정되시나요? 당뇨·고혈압·골다공증 등 상황별 임플란트 가능 여부와 시술 전 체크리스트를 정리했습니다.",
    date: "2026-02-14",
    readTime: "5분",
  },
  {
    id: 43,
    slug: "root-canal-pain-truth",
    category: "보존치료",
    tags: ["팩트체크"],
    title: "신경치료, 정말 아플까요?",
    subtitle: "신경치료 과정과 통증에 대한 오해와 진실",
    excerpt:
      "신경치료가 아프다는 이야기에 치료를 미루고 계신가요? 마취 기술의 발전으로 시술 중 통증은 거의 없습니다. 신경치료의 실제 과정과 통증 관리법을 솔직하게 알려드립니다.",
    date: "2026-02-14",
    readTime: "5분",
  },
  {
    id: 44,
    slug: "orthodontic-treatment-duration",
    category: "치아교정",
    tags: [],
    title: "교정, 얼마나 걸리나요?",
    subtitle: "케이스별로 알아보는 교정 기간 가이드",
    excerpt:
      "치아 교정을 시작하고 싶지만 기간이 걱정되시나요? 부분 교정 6개월부터 전체 교정 2년까지, 교정 유형과 치아 상태에 따른 예상 기간을 정리했습니다.",
    date: "2026-02-14",
    readTime: "5분",
  },
  {
    id: 45,
    slug: "clear-vs-bracket-orthodontics",
    category: "치아교정",
    tags: ["비교가이드"],
    title: "투명교정 vs 브라켓, 뭐가 맞을까?",
    subtitle: "나에게 맞는 교정 방법 선택 가이드",
    excerpt:
      "투명교정이 좋을까, 브라켓 교정이 좋을까? 심미성, 교정력, 편의성, 비용, 적합한 케이스까지 두 교정 방법의 장단점을 비교하여 올바른 선택을 도와드립니다.",
    date: "2026-02-14",
    readTime: "5분",
  },
  {
    id: 46,
    slug: "denture-adjustment-guide",
    category: "보철치료",
    tags: ["시니어"],
    title: "처음 틀니, 불편한 게 당연한가요?",
    subtitle: "틀니 적응 기간과 불편감 해결법 가이드",
    excerpt:
      "틀니를 처음 하면 누구나 불편합니다. 하지만 적응 기간을 잘 보내면 편안하게 사용할 수 있습니다. 적응 단계별 증상과 빠른 적응을 위한 핵심 요령을 안내합니다.",
    date: "2026-02-14",
    readTime: "5분",
  },
  {
    id: 47,
    slug: "scaling-frequency-guide",
    category: "예방·구강관리",
    tags: [],
    title: "스케일링, 얼마나 자주 받아야 하나요?",
    subtitle: "구강 상태별 적정 스케일링 주기 가이드",
    excerpt:
      "6개월? 1년? 스케일링 주기는 사람마다 다릅니다. 일반적인 권장 주기부터 잇몸 상태에 따른 맞춤 주기, 건강보험 적용까지 스케일링 주기의 모든 것을 정리했습니다.",
    date: "2026-02-14",
    readTime: "4분",
  },
];

/** slug로 포스트 전체 데이터 로드 (서버 전용) */
export async function getPostBySlug(slug: string) {
  const modules: Record<string, () => Promise<{ post: import("./types").BlogPost }>> = {
    "correct-brushing-method": () => import("./posts/correct-brushing-method"),
    "implant-aftercare-tips": () => import("./posts/implant-aftercare-tips"),
    "children-dental-care": () => import("./posts/children-dental-care"),
    "gum-disease-prevention": () => import("./posts/gum-disease-prevention"),
    "food-for-dental-health": () => import("./posts/food-for-dental-health"),
    "dental-floss-guide": () => import("./posts/dental-floss-guide"),
    "teeth-sensitivity-causes": () => import("./posts/teeth-sensitivity-causes"),
    "scaling-myths-and-facts": () => import("./posts/scaling-myths-and-facts"),
    "orthodontics-for-adults": () => import("./posts/orthodontics-for-adults"),
    "stress-and-teeth-grinding": () => import("./posts/stress-and-teeth-grinding"),
    "bad-breath-causes-and-solutions": () => import("./posts/bad-breath-causes-and-solutions"),
    "cavity-stages-and-treatment": () => import("./posts/cavity-stages-and-treatment"),
    "teeth-whitening-safety": () => import("./posts/teeth-whitening-safety"),
    "pregnancy-dental-care": () => import("./posts/pregnancy-dental-care"),
    "wisdom-teeth-extraction": () => import("./posts/wisdom-teeth-extraction"),
    "denture-vs-implant": () => import("./posts/denture-vs-implant"),
    "dry-mouth-syndrome": () => import("./posts/dry-mouth-syndrome"),
    "toothbrush-hygiene-tips": () => import("./posts/toothbrush-hygiene-tips"),
    "diabetes-and-dental-health": () => import("./posts/diabetes-and-dental-health"),
    "root-canal-and-crown": () => import("./posts/root-canal-and-crown"),
    "after-tooth-extraction-care": () => import("./posts/after-tooth-extraction-care"),
    "after-implant-surgery-care": () => import("./posts/after-implant-surgery-care"),
    "after-root-canal-care": () => import("./posts/after-root-canal-care"),
    "after-scaling-care": () => import("./posts/after-scaling-care"),
    "after-filling-care": () => import("./posts/after-filling-care"),
    "after-whitening-care": () => import("./posts/after-whitening-care"),
    "after-orthodontic-device-care": () => import("./posts/after-orthodontic-device-care"),
    "after-gum-surgery-care": () => import("./posts/after-gum-surgery-care"),
    "after-crown-prosthetic-care": () => import("./posts/after-crown-prosthetic-care"),
    "after-child-dental-treatment-care": () => import("./posts/after-child-dental-treatment-care"),
    "dental-xray-radiation-safety": () => import("./posts/dental-xray-radiation-safety"),
    "cracked-tooth-syndrome": () => import("./posts/cracked-tooth-syndrome"),
    "denture-care-tips": () => import("./posts/denture-care-tips"),
    "clear-aligner-care-guide": () => import("./posts/clear-aligner-care-guide"),
    "implant-vs-bridge-comparison": () => import("./posts/implant-vs-bridge-comparison"),
    "implant-pain-myths": () => import("./posts/implant-pain-myths"),
    "diabetes-and-implant": () => import("./posts/diabetes-and-implant"),
    "implant-lifespan-facts": () => import("./posts/implant-lifespan-facts"),
    "sealant-for-children": () => import("./posts/sealant-for-children"),
    "crown-material-comparison": () => import("./posts/crown-material-comparison"),
    "airflow-scaling-benefits": () => import("./posts/airflow-scaling-benefits"),
    "implant-eligibility-checklist": () => import("./posts/implant-eligibility-checklist"),
    "root-canal-pain-truth": () => import("./posts/root-canal-pain-truth"),
    "orthodontic-treatment-duration": () => import("./posts/orthodontic-treatment-duration"),
    "clear-vs-bracket-orthodontics": () => import("./posts/clear-vs-bracket-orthodontics"),
    "denture-adjustment-guide": () => import("./posts/denture-adjustment-guide"),
    "scaling-frequency-guide": () => import("./posts/scaling-frequency-guide"),
  };

  const loader = modules[slug];
  if (!loader) return null;
  const { post } = await loader();
  return post;
}
