import fs from "node:fs";
import path from "node:path";
import type { KeywordCategorySlug } from "../lib/admin-naver-datalab-keywords";
import type { HumanEvaluationLabel } from "../lib/keyword-candidate-evaluation";
import {
  getKeywordCandidateShadowAuditData,
  saveKeywordCandidateShadowAuditPreReviews,
} from "../lib/keyword-candidate-shadow-audit-store";

type Draft = Omit<HumanEvaluationLabel, "updatedAt" | "updatedBy">;

function loadEnvFile(filePath: string) {
  if (!fs.existsSync(filePath)) return;
  for (const line of fs.readFileSync(filePath, "utf8").split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const index = trimmed.indexOf("=");
    if (index <= 0) continue;
    const key = trimmed.slice(0, index).trim();
    const value = trimmed.slice(index + 1).trim().replace(/^['"]|['"]$/g, "");
    if (!(key in process.env)) process.env[key] = value;
  }
}

function relevant(purpose: Draft["purpose"]): Draft {
  return { relevance: "relevant", purpose, action: "approve", category: null, subgroup: null, notes: "" };
}

function taxonomy(category: KeywordCategorySlug, subgroup: string): Draft {
  return { relevance: "relevant", purpose: "taxonomy", action: "approve", category, subgroup, notes: "" };
}

function noise(notes: string): Draft {
  return { relevance: "irrelevant", purpose: "noise", action: "reject", category: null, subgroup: null, notes };
}

const V1_REVIEWS: Record<string, Draft> = {
  "안면비대칭경락": relevant("content"),
  "침냄새": relevant("faq"),
  "영통치과": relevant("local"),
  "마비스치약": relevant("product"),
  "암웨이치약": relevant("product"),
  "구내염원인": relevant("faq"),
  "사과나무치과": relevant("local"),
  "거북목교정": noise("치과보다 근골격계 치료 의도가 우세함"),
  "365치과": relevant("local"),
  "치과보험청구": relevant("content"),
  "고운미소치과": relevant("local"),
  "입벌리고자는이유": relevant("faq"),
  "턱관절통증치료": taxonomy("general-care", "턱관절/이갈이"),
  "이시림": taxonomy("restorative", "시림/균열"),
  "양악후기": relevant("content"),
  "안면비대칭": relevant("content"),
  "이빨교정비용": taxonomy("orthodontics", "비용/기간"),
  "금니판매가격": relevant("content"),
  "라미네이트가격": taxonomy("prosthetics", "라미네이트"),
  "칫솔": relevant("product"),
  "임플란트후기": relevant("content"),
  "치아레진가격": taxonomy("restorative", "레진"),
  "김포치과": relevant("local"),
  "양악수술후기": relevant("content"),
  "대치동치과": relevant("local"),
  "치과보험서류": relevant("content"),
  "송도치과": relevant("local"),
  "치과레진비용": taxonomy("restorative", "레진"),
  "혀가따가워요": relevant("faq"),
  "체외충격파가격": noise("정형외과·재활의학과 치료 의도"),
  "어금니임플란트후기": relevant("content"),
  "미금역치과": relevant("local"),
  "충치레진비용": taxonomy("restorative", "레진"),
  "입속염증": relevant("faq"),
  "침": { relevance: "uncertain", purpose: "unknown", action: "review", category: null, subgroup: null, notes: "타액과 침 치료의 검색 의도가 혼재함" },
  "치약추천": relevant("product"),
  "레진치료비용": taxonomy("restorative", "레진"),
  "구월동치과": relevant("local"),
  "프로바이오틱스유산균": noise("구강 전용이 아닌 일반 유산균 탐색어"),
  "치과신경치료비용": taxonomy("restorative", "신경치료"),
  "칫솔추천": relevant("product"),
  "왕타칫솔": relevant("product"),
  "센텀치과": relevant("local"),
  "깨진치아": relevant("faq"),
  "잇몸내려앉음": relevant("faq"),
  "속냄새": relevant("faq"),
  "혓바닥갈라짐": relevant("faq"),
  "목이물감": noise("이비인후과·소화기 검색 의도가 우세함"),
  "라미네이트후기": relevant("content"),
  "소화가안되는이유": noise("소화기 증상 검색어"),
  "압구정치과": relevant("local"),
  "인사돌": relevant("product"),
  "치과크라운비용": taxonomy("prosthetics", "크라운"),
  "치아교정": taxonomy("orthodontics", "종류/방법"),
  "여의도치과": relevant("local"),
  "휴대용칫솔살균기": relevant("product"),
  "입술비대칭": relevant("content"),
  "턱관절치료운동": relevant("content"),
  "이수역치과": relevant("local"),
  "불소치약": relevant("product"),
  "치과충치치료비용": taxonomy("restorative", "충치치료"),
  "뻐드렁니": taxonomy("orthodontics", "심미/고민"),
  "혀갈라짐": relevant("faq"),
  "코뿔소치약": relevant("product"),
  "일산치과": relevant("local"),
  "마곡치과": relevant("local"),
  "잇치치약": relevant("product"),
  "잇몸아픔": relevant("faq"),
  "구래동치과": relevant("local"),
  "치약": relevant("product"),
  "일회용수세미": noise("구강관리와 무관한 생활용품"),
  "얼굴비대칭": relevant("content"),
  "치아보험청구서류": relevant("content"),
  "교정비용": taxonomy("orthodontics", "비용/기간"),
  "무삭제라미네이트후기": relevant("content"),
  "치아크라운가격": taxonomy("prosthetics", "크라운"),
  "구강유산균": relevant("product"),
  "안면비대칭한의원": relevant("content"),
  "고불소치약": relevant("product"),
  "얼굴비대칭교정": relevant("content"),
  "도수치료비용": noise("정형외과·재활의학과 치료 의도"),
  "지르코니아크라운가격": taxonomy("prosthetics", "소재/종류"),
  "2080치약": relevant("product"),
  "콜게이트치약": relevant("product"),
  "돌출입수술비용": relevant("content"),
  "연세치과": relevant("local"),
  "검단치과": relevant("local"),
  "턱끝전진술후기": relevant("content"),
  "아기칫솔": relevant("product"),
  "애터미치약": relevant("product"),
  "치아파절": relevant("faq"),
  "치아신경치료": taxonomy("restorative", "신경치료"),
  "언청이": noise("구순구개열 전문 진료 의도가 우세함"),
  "운정치과": relevant("local"),
  "편도암": noise("이비인후과 종양 검색어"),
  "산본치과": relevant("local"),
  "치아보험후기": relevant("content"),
  "크라운치료비용": taxonomy("prosthetics", "크라운"),
  "턱관절치료병원": taxonomy("general-care", "턱관절/이갈이"),
  "후두암초기증상": noise("이비인후과 종양 검색어"),
};

const V2_REVIEWS: Record<string, Draft> = {
  "턱관절보톡스": taxonomy("general-care", "턱관절/이갈이"),
  "치과크라운": taxonomy("prosthetics", "크라운"),
  "코도모칫솔": relevant("product"),
  "탕정치과": relevant("local"),
  "혀클리너": relevant("product"),
  "인계동치과": relevant("local"),
  "스켈링비용": taxonomy("prevention", "스케일링"),
  "입안이헐었을때": relevant("faq"),
  "턱관절치과": taxonomy("general-care", "턱관절/이갈이"),
  "교정치과": relevant("local"),
  "입안염증": relevant("faq"),
  "안면비대칭교정가격": relevant("content"),
  "얼굴비대칭한의원": relevant("content"),
  "구강스프레이": relevant("product"),
  "양악수술": relevant("content"),
  "건대치과": relevant("local"),
  "턱통증": relevant("faq"),
  "수원치과": relevant("local"),
  "치아보험면책기간": relevant("content"),
  "오랄비치실": relevant("product"),
  "하루플란트치과": relevant("local"),
  "구내염": relevant("faq"),
  "턱비대칭": taxonomy("orthodontics", "심미/고민"),
  "구강작열감증후군": relevant("faq"),
  "돌출입": taxonomy("orthodontics", "심미/고민"),
  "치과보험": relevant("content"),
  "치아보험가입조건": relevant("content"),
  "강남치과": relevant("local"),
  "파로돈탁스치약": relevant("product"),
  "치과레진": taxonomy("restorative", "레진"),
  "설염원인": relevant("faq"),
  "치과교정비용": taxonomy("orthodontics", "비용/기간"),
  "현대해상치아보험": relevant("content"),
  "아프타성구내염": relevant("faq"),
  "닥터재일치과": relevant("local"),
  "혀백태원인": relevant("faq"),
  "구내염증상": relevant("faq"),
  "치아보험서류": relevant("content"),
  "치아교정기": taxonomy("orthodontics", "종류/방법"),
  "치과치료종류": relevant("content"),
  "뷰센칫솔": relevant("product"),
  "충치": taxonomy("restorative", "충치치료"),
  "구강청결제": relevant("product"),
  "KB치아보험": relevant("content"),
  "잇몸통증": taxonomy("prevention", "잇몸질환/치료"),
  "오랄비칫솔": relevant("product"),
  "안면비대칭마사지": noise("마사지·경락 탐색 의도가 우세함"),
  "설염": relevant("faq"),
  "턱관절장애": taxonomy("general-care", "턱관절/이갈이"),
  "치아교정비": taxonomy("orthodontics", "비용/기간"),
  "철산치과": relevant("local"),
  "입병": relevant("faq"),
  "혓바닥염증": relevant("faq"),
  "혓바닥백태": relevant("faq"),
  "양악수술전후": relevant("content"),
  "치과치료확인서": relevant("content"),
  "혀통증": relevant("faq"),
  "치과치료": relevant("content"),
  "치아보험추천": relevant("content"),
  "역삼역치과": relevant("local"),
  "네고왕치약": relevant("product"),
  "앞니교정비용": taxonomy("orthodontics", "비용/기간"),
  "아랫니교정": taxonomy("orthodontics", "종류/방법"),
  "앞니벌어짐": taxonomy("orthodontics", "심미/고민"),
  "잠실치과": relevant("local"),
  "혓바닥통증": relevant("faq"),
  "치아보험": relevant("content"),
  "이빨교정": taxonomy("orthodontics", "종류/방법"),
  "레진가격": taxonomy("restorative", "레진"),
  "근처치과": relevant("local"),
  "향남치과": relevant("local"),
  "칫솔꽂이": relevant("product"),
  "가루치약": relevant("product"),
  "치아보험다이렉트": relevant("content"),
  "로덴치과": relevant("local"),
  "혀갈라짐치료": relevant("faq"),
  "민티드고체치약": relevant("product"),
  "히말라야핑크솔트치약": relevant("product"),
  "연산동치과": relevant("local"),
  "치과": relevant("local"),
  "스마트치과": relevant("local"),
  "죽염치약": relevant("product"),
  "어금니칫솔": relevant("product"),
  "재신경치료": taxonomy("restorative", "신경치료"),
  "병점치과": relevant("local"),
  "명동치과": relevant("local"),
  "칫솔걸이": relevant("product"),
  "고체치약": relevant("product"),
  "입안헐었을때": relevant("faq"),
  "잇몸염증": taxonomy("prevention", "잇몸질환/치료"),
  "메리츠치아보험": relevant("content"),
  "오스템칫솔": relevant("product"),
  "안면비대칭교정": relevant("content"),
  "페리오치약": relevant("product"),
  "광화문치과": relevant("local"),
  "치솔": relevant("product"),
  "연세퍼스트치과": relevant("local"),
  "구내염빨리낫는법": relevant("faq"),
  "부정교합교정기": taxonomy("orthodontics", "종류/방법"),
  "안면비대칭수술": relevant("content"),
};

const V3_REVIEWS: Record<string, Draft> = {
  "구강궤양": relevant("faq"),
  "구강염": relevant("faq"),
  "턱끝수술": relevant("content"),
  "부천치과": relevant("local"),
  "양악": relevant("content"),
  "선릉역치과": relevant("local"),
  "교정기": taxonomy("orthodontics", "종류/방법"),
  "오아구강세정기": relevant("product"),
  "혀통증병원": relevant("faq"),
  "잇몸고름주머니": relevant("faq"),
  "부정교합": taxonomy("orthodontics", "심미/고민"),
  "도요다크라운": noise("자동차 Toyota Crown 탐색어"),
  "첨단칫솔": relevant("product"),
  "쇼그렌증후군": relevant("faq"),
  "삼성역치과": relevant("local"),
  "앞니교정": taxonomy("orthodontics", "종류/방법"),
  "서울치과": relevant("local"),
  "서현역치과": relevant("local"),
  "AXA치아보험": relevant("content"),
  "CROWN": { relevance: "uncertain", purpose: "unknown", action: "review", category: null, subgroup: null, notes: "치과 크라운과 일반 영문 검색 의도가 혼재함" },
  "잇몸부었을때": relevant("faq"),
  "임산부치약": relevant("product"),
  "치아크라운비용": taxonomy("prosthetics", "크라운"),
  "어린이치아보험": relevant("content"),
  "설염병원": relevant("faq"),
  "유지장치가격": taxonomy("orthodontics", "유지장치/재교정"),
  "미백치약": relevant("product"),
  "부산치과": relevant("local"),
  "혀백태제거": relevant("faq"),
  "잇몸고름": relevant("faq"),
  "치과미백가격": taxonomy("prosthetics", "치아미백"),
  "오랄비": relevant("product"),
  "태전동치과": relevant("local"),
  "설측교정비용": taxonomy("orthodontics", "종류/방법"),
  "철산역치과": relevant("local"),
  "어린이치약": relevant("product"),
  "잇몸염증고름": relevant("faq"),
  "유아칫솔": relevant("product"),
  "크라운치료가격": taxonomy("prosthetics", "크라운"),
  "치약짜개": relevant("product"),
  "치약순위": relevant("product"),
  "치과보험추천": relevant("content"),
  "잇몸치약": relevant("product"),
  "구내염치료": relevant("faq"),
  "신사역치과": relevant("local"),
  "실속보장치아보험": relevant("content"),
  "태국치약": relevant("product"),
  "신논현역치과": relevant("local"),
  "구강염증": relevant("faq"),
  "틀니가격": taxonomy("prosthetics", "틀니"),
  "구내염병원": relevant("faq"),
  "치아보험고지의무": relevant("content"),
  "야탑치과": relevant("local"),
  "구내염약": relevant("faq"),
  "치아보험바로보장": relevant("content"),
  "우만동치과": relevant("local"),
  "턱관절스플린트": taxonomy("general-care", "턱관절/이갈이"),
  "교보생명치아보험": relevant("content"),
  "혀백태": relevant("faq"),
  "치과의료보험": relevant("content"),
  "다이렉트치아보험": relevant("content"),
  "치아보험비교사이트": relevant("content"),
  "턱관절장애병원": taxonomy("general-care", "턱관절/이갈이"),
  "구강암": relevant("faq"),
  "파나소닉구강세정기": relevant("product"),
  "토요다크라운": noise("자동차 Toyota Crown 탐색어"),
  "치아교정가격": taxonomy("orthodontics", "비용/기간"),
  "농협치아보험": relevant("content"),
  "잇몸이부었을때": relevant("faq"),
  "치간칫솔사이즈": relevant("product"),
  "여행용칫솔": relevant("product"),
  "오아워터픽": relevant("product"),
  "대연동치과": relevant("local"),
  "구강편평태선": relevant("faq"),
  "치과실비": relevant("content"),
  "치아보험비교": relevant("content"),
  "구강작열감": relevant("faq"),
  "일본치약": relevant("product"),
  "미세모칫솔": relevant("product"),
  "한화치아보험": relevant("content"),
  "독산동치과": relevant("local"),
  "앞니부분교정비용": taxonomy("orthodontics", "종류/방법"),
  "아랫니부분교정": taxonomy("orthodontics", "종류/방법"),
  "메리츠화재치아보험": relevant("content"),
  "수영구치과": relevant("local"),
  "과개교합교정": taxonomy("orthodontics", "심미/고민"),
  "상동치과": relevant("local"),
  "치간치솔": relevant("product"),
  "천호치과": relevant("local"),
  "가정동치과": relevant("local"),
  "동부화재치아보험": relevant("content"),
  "스케일링가격": taxonomy("prevention", "스케일링"),
  "캔트칫솔": relevant("product"),
  "미아사거리치과": relevant("local"),
  "덧니": taxonomy("orthodontics", "심미/고민"),
  "눈매교정": noise("안과·성형외과 검색 의도"),
  "플란트치과": relevant("local"),
  "혀설태": relevant("faq"),
  "치과보험비교": relevant("content"),
  "켄트치약": relevant("product"),
};

const V4_REVIEWS: Record<string, Draft> = {
  "덧니교정비용": taxonomy("orthodontics", "비용/기간"),
  "치아보험금액": relevant("content"),
  "휴대용칫솔세트": relevant("product"),
  "치아보험중복보장": relevant("content"),
  "새마을금고치아보험": relevant("content"),
  "잇몸에서피": relevant("faq"),
  "어린이치과보험": relevant("content"),
  "휴대용워터픽": relevant("product"),
  "부분틀니가격": taxonomy("prosthetics", "틀니"),
  "치아교정치과": relevant("local"),
  "과개교합": taxonomy("orthodontics", "심미/고민"),
  "실비보험치과": relevant("content"),
  "치아보험가격": relevant("content"),
  "비타민치과": relevant("local"),
  "앞니신경치료": taxonomy("restorative", "신경치료"),
  "40대치아교정": taxonomy("orthodontics", "대상/나이"),
  "사당역치과": relevant("local"),
  "치과레진가격": taxonomy("restorative", "레진"),
  "온마음치과": relevant("local"),
  "금이빨팔기": relevant("content"),
  "판교치과": relevant("local"),
  "래디어스칫솔": relevant("product"),
  "잇몸": taxonomy("prevention", "잇몸질환/치료"),
  "금이빨가격": relevant("content"),
  "소금치약": relevant("product"),
  "입안건조": relevant("faq"),
  "입안마름": relevant("faq"),
  "삼성동치과": relevant("local"),
  "아랫니교정비용": taxonomy("orthodontics", "비용/기간"),
  "아기치아보험": relevant("content"),
  "치실": relevant("product"),
  "투명교정가격": taxonomy("orthodontics", "종류/방법"),
  "구강내과": relevant("local"),
  "신매동치과": relevant("local"),
  "상악동거상술비용": taxonomy("implant", "뼈이식/골증대"),
  "앞니라미네이트가격": taxonomy("prosthetics", "라미네이트"),
  "주걱턱수술": relevant("content"),
  "치과실손보험": relevant("content"),
  "구내염치료병원": relevant("faq"),
  "계면활성제없는치약": relevant("product"),
  "유아치약": relevant("product"),
  "혀백태치료": relevant("faq"),
  "교보치아보험": relevant("content"),
  "공덕치과": relevant("local"),
  "일회용칫솔": relevant("product"),
  "치과치아미백가격": taxonomy("prosthetics", "치아미백"),
  "디에르치과": relevant("local"),
  "문산치과": relevant("local"),
  "치아보험가입": relevant("content"),
  "발치교정": taxonomy("orthodontics", "종류/방법"),
  "치아재신경치료": taxonomy("restorative", "신경치료"),
  "잇몸피": relevant("faq"),
  "휴대용칫솔": relevant("product"),
  "구강건조": taxonomy("prevention", "구강건조/타액"),
  "구강": { relevance: "uncertain", purpose: "unknown", action: "review", category: null, subgroup: null, notes: "범위가 지나치게 넓어 구체적인 검색 의도를 확정하기 어려움" },
  "강남구치과": relevant("local"),
  "잇몸염증치료": taxonomy("prevention", "잇몸질환/치료"),
  "강남역치과": relevant("local"),
  "입마름병": relevant("faq"),
  "미국치약": relevant("product"),
  "치과치료실비": relevant("content"),
  "독일치약": relevant("product"),
  "구강암수술": relevant("faq"),
  "음파전동칫솔": relevant("product"),
  "실비보험치과치료": relevant("content"),
  "대나무칫솔": relevant("product"),
  "오아전동칫솔": relevant("product"),
  "치아뿌리염증": relevant("faq"),
  "검단신도시치과": relevant("local"),
  "365열린치과": relevant("local"),
  "잇몸영양제": relevant("product"),
  "현대해상치과보험": relevant("content"),
  "20대치과보험": relevant("content"),
  "인플란트가격": taxonomy("implant", "비용/가격"),
  "미아사거리역치과": relevant("local"),
  "다이소치간칫솔": relevant("product"),
  "한쪽턱관절": relevant("faq"),
  "구내염한의원": relevant("content"),
  "구강스펀지": relevant("product"),
  "스플린트": taxonomy("general-care", "턱관절/이갈이"),
  "티타드칫솔": relevant("product"),
  "치아보험해지": relevant("content"),
  "성인치아교정": taxonomy("orthodontics", "대상/나이"),
  "입안건조증": taxonomy("prevention", "구강건조/타액"),
  "발산역치과": relevant("local"),
  "앞니부분교정": taxonomy("orthodontics", "종류/방법"),
  "잇몸이붓고아플때": relevant("faq"),
  "새롬동치과": relevant("local"),
  "구강내과전문의": relevant("local"),
  "치과칫솔": relevant("product"),
  "상무지구치과": relevant("local"),
  "잇몸파임": relevant("faq"),
  "아이치아보험": relevant("content"),
  "주안치과": relevant("local"),
  "화정치과": relevant("local"),
  "펌핑치약": relevant("product"),
  "유아치아보험": relevant("content"),
  "금천구치과": relevant("local"),
  "턱끝전진술": relevant("content"),
  "칫솔케이스": relevant("product"),
};

async function main() {
  loadEnvFile(path.resolve(process.cwd(), ".env"));
  loadEnvFile(path.resolve(process.cwd(), ".env.local"));
  const audit = await getKeywordCandidateShadowAuditData();
  const reviews = audit.engineVersion === "keyword-shadow-v1"
    ? V1_REVIEWS
    : audit.engineVersion === "keyword-shadow-v2"
      ? V2_REVIEWS
      : audit.engineVersion === "keyword-shadow-v3"
        ? V3_REVIEWS
        : audit.engineVersion === "keyword-shadow-v4"
          ? V4_REVIEWS
        : null;
  if (!reviews) throw new Error(`지원하지 않는 감사 엔진입니다: ${audit.engineVersion}`);
  const keywords = new Set(audit.items.map((item) => item.keyword));
  const missing = audit.items.filter((item) => !reviews[item.keyword]).map((item) => item.keyword);
  const extras = Object.keys(reviews).filter((keyword) => !keywords.has(keyword));
  if (missing.length > 0 || extras.length > 0) {
    throw new Error(`감사 큐 불일치: missing=${missing.join(",")}; extras=${extras.join(",")}`);
  }
  const result = await saveKeywordCandidateShadowAuditPreReviews(
    audit.items.map((item) => ({ id: item.id, label: reviews[item.keyword] })),
    `assistant-assisted-pre-review:${audit.engineVersion}`,
  );
  const counts = Object.fromEntries(["taxonomy", "content", "faq", "product", "local", "noise", "unknown"].map((purpose) => [
    purpose,
    Object.values(reviews).filter((review) => review.purpose === purpose).length,
  ]));
  console.log(JSON.stringify({ ...result, counts }, null, 2));
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
